In [2]:
import numpy as np

# Create two matrices using NumPy arrays
matrix1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

matrix2 = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

# Add the two matrices
result = matrix1 + matrix2

# Display the matrices
print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nAddition of two matrices:")
print(result)


Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8  9]
 [10 11 12]]

Addition of two matrices:
[[ 8 10 12]
 [14 16 18]]
